#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Determine OS and run appropriate command
case "$(uname -s)" in
CYGWIN* | MINGW* | MSYS* | Windows*)
    # Windows-specific commands if needed
    echo "Running pre-commit checks for Windows..."
    echo "..............."
    npm run lint
    ;;
*)
    # Linux/macOS commands
    echo "Running pre-commit checks for Linux/macOS..."
    echo "..............."
    npm run lint
    ;;
esac
